<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>raven-mongodb</artifactId>
        <groupId>io.github.raven-source</groupId>
        <version>3.2.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <description>raven mongodb repository</description>
    <url>https://github.com/Raven-Source/raven-mongodb-java</url>

    <artifactId>raven-mongodb-reactive</artifactId>
    <packaging>jar</packaging>

    <properties>
        <reactor.version>3.6.12</reactor.version>
        <reactive-streams.version>1.0.4</reactive-streams.version>
    </properties>

    <dependencies>

        <dependency>
            <groupId>io.github.raven-source</groupId>
            <artifactId>raven-mongodb-core</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongodb-driver-reactivestreams</artifactId>
            <!--<exclusions>
                <exclusion>
                    <groupId>org.reactivestreams</groupId>
                    <artifactId>reactive-streams</artifactId>
                </exclusion>
            </exclusions>-->
        </dependency>

        <!--<dependency>
            <groupId>org.reactivestreams</groupId>
            <artifactId>reactive-streams</artifactId>
            <version>${reactive-streams.version}</version>
        </dependency>-->

        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
            <version>${reactor.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>io.github.raven-source</groupId>
            <artifactId>raven-mongodb-core</artifactId>
            <version>${project.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>

    </dependencies>

</project>